title: Drafts
theme: jekyll-theme-minimal
baseurl:

app-store-url: https://itunes.apple.com/app/id1236254471?ls=1&mt=8&at=11l4Cf&ct=site
google_analytics: UA-1639692-22

twitter:
  username: draftsapp
facebook:
  publisher: https://www.facebook.com/draftsapp
social:
  name: Drafts App
  links:
    - http://twitter.com/draftsapp
    - https://www.facebook.com/draftsapp
image: http://getdrafts.com/images/drafts-ogimage.png
